apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: hello
  namespace: hello
namespace: hello
resources:
  - deployment.yaml
  - service.yaml
  - config-map.yaml
  - namespace.yaml